# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: UTF-8
  database: edutest
  host: localhost
  pool: 5
  username: postgres
  password: password
